import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian Agüero
 */
public class fondoNice extends javax.swing.JFrame {
    
            boolean entrada = true;
            double CambiarSigno = 0.0;
            String SignoCambiado = "";
            double Suma = 0.0;
            double Suma2 = 0.0;
            double Resta = 0.0;
            double Resta2 = 0.0;
            double Multiplicacion = 0.0;
            double Multiplicacion2 = 0.0;
            double Division = 0.0;
            double Division2 = 0.0;
            String Numero = "";
            double Operacion = 0.0;
            int TipoDeOperacion = 0;

    public fondoNice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Display = new javax.swing.JTextField();
        BtnC = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        BtnPunto = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnDividir = new javax.swing.JButton();
        BtnMultiplicar = new javax.swing.JButton();
        BtnRestar = new javax.swing.JButton();
        BtnSuma = new javax.swing.JButton();
        Marca = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        BtnSigno = new javax.swing.JButton();
        BtnAC = new javax.swing.JButton();
        PanelSolar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(102, 0, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        setIconImage(getIconImage());
        setName("Calculadora"); // NOI18N
        setResizable(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        Display.setBackground(new java.awt.Color(204, 204, 255));
        Display.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        Display.setForeground(new java.awt.Color(153, 0, 153));
        Display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Display.setText("0");
        Display.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Display.setMaximumSize(new java.awt.Dimension(0, 15));
        Display.setMinimumSize(new java.awt.Dimension(0, 15));
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        Display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DisplayKeyTyped(evt);
            }
        });

        BtnC.setBackground(new java.awt.Color(153, 0, 153));
        BtnC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnC.setText("C");
        BtnC.setBorder(null);
        BtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCActionPerformed(evt);
            }
        });

        Btn4.setBackground(new java.awt.Color(153, 0, 153));
        Btn4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn4.setText("4");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn7.setBackground(new java.awt.Color(153, 0, 153));
        Btn7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn7.setText("7");
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn0.setBackground(new java.awt.Color(153, 0, 153));
        Btn0.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn0.setText("0");
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        Btn8.setBackground(new java.awt.Color(153, 0, 153));
        Btn8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn8.setText("8");
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn2.setBackground(new java.awt.Color(153, 0, 153));
        Btn2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn2.setText("2");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn5.setBackground(new java.awt.Color(153, 0, 153));
        Btn5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn5.setText("5");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        BtnPunto.setBackground(new java.awt.Color(153, 0, 153));
        BtnPunto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BtnPunto.setText(".");
        BtnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPuntoActionPerformed(evt);
            }
        });

        Btn1.setBackground(new java.awt.Color(153, 0, 153));
        Btn1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn1.setText("1");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn9.setBackground(new java.awt.Color(153, 0, 153));
        Btn9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn9.setText("9");
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        Btn6.setBackground(new java.awt.Color(153, 0, 153));
        Btn6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn6.setText("6");
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        Btn3.setBackground(new java.awt.Color(153, 0, 153));
        Btn3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btn3.setText("3");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        BtnIgual.setBackground(new java.awt.Color(153, 0, 153));
        BtnIgual.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnIgual.setText("=");
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnDividir.setBackground(new java.awt.Color(153, 0, 153));
        BtnDividir.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnDividir.setText("/");
        BtnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDividirActionPerformed(evt);
            }
        });

        BtnMultiplicar.setBackground(new java.awt.Color(153, 0, 153));
        BtnMultiplicar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnMultiplicar.setText("*");
        BtnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultiplicarActionPerformed(evt);
            }
        });

        BtnRestar.setBackground(new java.awt.Color(153, 0, 153));
        BtnRestar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnRestar.setText("-");
        BtnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestarActionPerformed(evt);
            }
        });

        BtnSuma.setBackground(new java.awt.Color(153, 0, 153));
        BtnSuma.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnSuma.setText("+");
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        Marca.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Marca.setForeground(new java.awt.Color(255, 51, 255));
        Marca.setText("AGÜERO");
        Marca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcaMouseClicked(evt);
            }
        });

        Modelo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Modelo.setForeground(new java.awt.Color(255, 0, 255));
        Modelo.setText("MCU-V1CAR");
        Modelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModeloMouseClicked(evt);
            }
        });

        BtnSigno.setBackground(new java.awt.Color(153, 0, 153));
        BtnSigno.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnSigno.setText("+/-");
        BtnSigno.setBorder(null);
        BtnSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignoActionPerformed(evt);
            }
        });

        BtnAC.setBackground(new java.awt.Color(153, 0, 153));
        BtnAC.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnAC.setText("AC");
        BtnAC.setBorder(null);
        BtnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnACActionPerformed(evt);
            }
        });

        PanelSolar.setBackground(new java.awt.Color(51, 51, 0));
        PanelSolar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout PanelSolarLayout = new javax.swing.GroupLayout(PanelSolar);
        PanelSolar.setLayout(PanelSolarLayout);
        PanelSolarLayout.setHorizontalGroup(
            PanelSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        PanelSolarLayout.setVerticalGroup(
            PanelSolarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Modelo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtnSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(Btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(BtnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Marca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PanelSolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modelo)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(BtnSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "5");
        }
        
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "2");
        }
    }//GEN-LAST:event_Btn2ActionPerformed

    private void DisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DisplayKeyTyped
        int key = evt.getKeyChar();
        
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }

        boolean numeros = key >= 48 && key <= 57 || key == 46;
        
        if (!numeros){
            evt.consume();
        }

        if (Display.getText().trim().length() == 16) {
            evt.consume();
        }
        
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.'){
            evt.consume();
        }
        
        if(evt.getKeyChar() == '.' && Display.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_DisplayKeyTyped

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
            if(entrada){
                for(int i = 0; i <= 1; i++){
                    if (Display.getText().length() >= 1){
                        Display.setText(null);
                    }
                }
                entrada = false;
            }    
        
            if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "7");
        }
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
       if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "3");
        }
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "8");
        }
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "9");
        }
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "4");
        }
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "6");
        }
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "1");
        }
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        if(entrada){
            for(int i = 0; i <= 1; i++){
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
            }
            entrada = false;
        }
        
        if (Display.getText().trim().length() < 16) {
            this.Display.setText( this.Display.getText() + "0");
        }
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPuntoActionPerformed
       if(entrada){
            for(int i = 0; i <= 1; i++){
                
                if (Display.getText().length() >= 1){
                    Display.setText(null);
                }
 
            }
            entrada = false;
            
        }
        
       if (Display.getText().trim().length() < 16) {
            if("".equals(this.Display.getText())){
                this.Display.setText(this.Display.getText() + "0.");
            }
            
        else{
            if(!Punto(this.Display.getText())){
                this.Display.setText(this.Display.getText() + ".");
            }
        }
        }
    }//GEN-LAST:event_BtnPuntoActionPerformed

    public static boolean Punto(String Cadena){
        
        boolean Resultado = false;
        
        for(int i = 0; i < Cadena.length(); i++){
            if(Cadena.substring(i, i+1).equals(".")){
                Resultado = true;
                break;
            }
        }
        
        return Resultado;
    }
    
    private void BtnSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignoActionPerformed
        if ("Math.Error".equals(this.Display.getText()) || "Christian Agüero 2022".equals(this.Display.getText()) || "".equals(this.Display.getText())){
            this.Display.setText("0");    
        }
        
        else{
            if("0".equals(this.Display.getText())){
                
                entrada = true;
            }else if ("-".equals(this.Display.getText())){
                
                } else{
                    CambiarSigno = Double.parseDouble(this.Display.getText());
                    CambiarSigno = CambiarSigno * -1;
            
                    if(CambiarSigno % 1 == 0){
                        SignoCambiado = String.valueOf(String.format("%16.0f", CambiarSigno));
                    } else{
                        SignoCambiado = String.valueOf(CambiarSigno);
                    }
            
                    this.Display.setText(SignoCambiado);
                }
        }
    }//GEN-LAST:event_BtnSignoActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void BtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCActionPerformed
       if ("Math.Error".equals(this.Display.getText()) || "Christian Agüero 2022".equals(this.Display.getText()) || "".equals(this.Display.getText())){
            this.Display.setText("0");   
        }
       
       else{
            if(!"0".equals(this.Display.getText())){
             this.Display.setText(this.Display.getText().substring(0, this.Display.getText().length()-1));
            }
        
            if(Display.getText().length() == 0){
                this.Display.setText("0");
            }
        
            if("".equals(this.Display.getText())){
                this.Display.setText("0");
            }
       }
        
        entrada = true;
    }//GEN-LAST:event_BtnCActionPerformed

    private void BtnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnACActionPerformed
        if (Display.getText().length() >= 1 || "".equals(this.Display.getText())){
                this.Display.setText("0");
        }
            
        entrada = true;
    }//GEN-LAST:event_BtnACActionPerformed

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        if ("Math.Error".equals(this.Display.getText()) || "Christian Agüero 2022".equals(this.Display.getText())){
            this.Display.setText("0");   
        }
        
        else{
            if ("".equals(this.Display.getText())){
                
            }else{
                Suma = Double.parseDouble(this.Display.getText());
                this.Display.setText("");
                TipoDeOperacion = 1;
            }
        }
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
            if("".equals(this.Display.getText()) || "Math.Error".equals(this.Display.getText()) || "Christian Agüero 2022".equals(this.Display.getText())){
                
            }else{
                switch (TipoDeOperacion) {
                    case 1:
                        Suma2 = Double.parseDouble(this.Display.getText());
                        Operacion = Suma + Suma2;
                        break;
                    case 2:
                        Resta2 = Double.parseDouble(this.Display.getText());
                        Operacion = Resta - Resta2;
                        break;
                    case 3:
                        Multiplicacion2 = Double.parseDouble(this.Display.getText());
                        Operacion = Multiplicacion * Multiplicacion2;
                        break;
                    case 4:
                        Division2 = Double.parseDouble(this.Display.getText());
                        if(Division2 == 0){
                            Numero = "Math.Error";
                        }else{
                            Operacion = Division / Division2;
                        }           
                        break;
                    default:
                        Operacion = Double.parseDouble(this.Display.getText());
                        break;
                }
           
                if("".equals(Numero)){
                    if(Operacion % 1 == 0){
                        Numero = String.valueOf(String.format("%16.0f", Operacion));
                        this.Display.setText(Numero);
                    } else{
                        Numero = String.valueOf(Operacion);
                        this.Display.setText(Numero);
                    }
                }else{
                    this.Display.setText(Numero);
                }
                
            entrada = true;
            TipoDeOperacion = 0;
            Numero = "";
        }
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestarActionPerformed
        if ("Math.Error".equals(this.Display.getText()) || "Christian Agüero 2022".equals(this.Display.getText())){
            this.Display.setText("0");    
        }
        
        else{
            if("".equals(this.Display.getText())){
                
            }else{
                Resta = Double.parseDouble(this.Display.getText());
                this.Display.setText("");
                TipoDeOperacion = 2;
            }
        }
    }//GEN-LAST:event_BtnRestarActionPerformed

    private void BtnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultiplicarActionPerformed
        if ("Math.Error".equals(this.Display.getText()) || "Christian Agüero 2022".equals(this.Display.getText())){
            this.Display.setText("0");    
        }
        
        else{
            if ("".equals(this.Display.getText())){
                
            }else{
                Multiplicacion = Double.parseDouble(this.Display.getText());
                this.Display.setText("");
                TipoDeOperacion = 3;
            }
        }
    }//GEN-LAST:event_BtnMultiplicarActionPerformed

    private void BtnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDividirActionPerformed
        if ("Math.Error".equals(this.Display.getText()) || "Christian Agüero 2022".equals(this.Display.getText())){
            this.Display.setText("0");
        }
        
        else{
            if ("Christian Agüero 2022".equals(this.Display.getText())){
                this.Display.setText("0");
            }
        
            if ("".equals(this.Display.getText())){
                
            }else{
                Division = Double.parseDouble(this.Display.getText());
                this.Display.setText("");
                TipoDeOperacion = 4;
            }
        }
    }//GEN-LAST:event_BtnDividirActionPerformed

    private void ModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModeloMouseClicked
        this.Display.setText("Christian Agüero 2022");
    }//GEN-LAST:event_ModeloMouseClicked

    private void MarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcaMouseClicked
        String nombre = "";
        
        nombre = JOptionPane.showInputDialog(null, "Gracias por escogernos, dame tu nobre", "Bienvenida", JOptionPane.QUESTION_MESSAGE);
        
        if(null == nombre){
            
        }else   switch (nombre) {
                    case "":
                        break;
                    case "Christian Aguero":
                        JOptionPane.showMessageDialog(null, "Oh por dios es el jefe, bienvenido Sr. " + nombre + " Romero", "Bienvenida", JOptionPane.INFORMATION_MESSAGE);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Hola " + nombre + " Te damos la bienvenida", "Bienvenida", JOptionPane.INFORMATION_MESSAGE);
                        break;
                }
    }//GEN-LAST:event_MarcaMouseClicked
    //JRadioButton y JCheckBox
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fondoNice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fondoNice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fondoNice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fondoNice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fondoNice().setVisible(true);
                
            }
        });
    }
    
@Override
    public Image getIconImage() {
    Image retValue = Toolkit.getDefaultToolkit().
    getImage(ClassLoader.getSystemResource("Icono/Calculadora.png"));


    return retValue;
} 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnAC;
    private javax.swing.JButton BtnC;
    private javax.swing.JButton BtnDividir;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnMultiplicar;
    private javax.swing.JButton BtnPunto;
    private javax.swing.JButton BtnRestar;
    private javax.swing.JButton BtnSigno;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JTextField Display;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JPanel PanelSolar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
